name: note_app_hive_flutter
description: Todo app using clean architecture flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.3
  path_provider: ^2.0.11
  dartz: ^0.10.1
  equatable: ^2.0.3
  provider: ^6.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  hive_generator: ^1.1.3


flutter:
  uses-material-design: true































